import type {Metadata} from 'next'
import {Urbanist} from 'next/font/google'
import './globals.css'

const urbanist = Urbanist({
  subsets: ['latin'], // Bạn có thể chọn thêm các subset khác nếu cần
  weight: ['400', '500', '700'], // Chọn các weight bạn cần
  style: ['normal', 'italic'], // Các kiểu cần thiết
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${urbanist.className}  antialiased`}>{children}</body>
    </html>
  )
}
